// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4w-lGuylxXOsctjVFEpVtk_P4NtUKjFU',
    appId: '1:1000646821625:web:67b36ac9240351ca46c428',
    messagingSenderId: '1000646821625',
    projectId: 'mindmate-f92b2',
    authDomain: 'mindmate-f92b2.firebaseapp.com',
    storageBucket: 'mindmate-f92b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirLBKUtZT2PHRD8z9BqOxWk0-sQEHO3M',
    appId: '1:1000646821625:android:1410e6f6636779cd46c428',
    messagingSenderId: '1000646821625',
    projectId: 'mindmate-f92b2',
    storageBucket: 'mindmate-f92b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCha0PtPHy-R53tOPX0pTHX9s59-d_PwTw',
    appId: '1:1000646821625:ios:cfd137d2957d43cc46c428',
    messagingSenderId: '1000646821625',
    projectId: 'mindmate-f92b2',
    storageBucket: 'mindmate-f92b2.appspot.com',
    iosBundleId: 'com.example.mindMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCha0PtPHy-R53tOPX0pTHX9s59-d_PwTw',
    appId: '1:1000646821625:ios:cfd137d2957d43cc46c428',
    messagingSenderId: '1000646821625',
    projectId: 'mindmate-f92b2',
    storageBucket: 'mindmate-f92b2.appspot.com',
    iosBundleId: 'com.example.mindMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4w-lGuylxXOsctjVFEpVtk_P4NtUKjFU',
    appId: '1:1000646821625:web:42a90239d1fb84e046c428',
    messagingSenderId: '1000646821625',
    projectId: 'mindmate-f92b2',
    authDomain: 'mindmate-f92b2.firebaseapp.com',
    storageBucket: 'mindmate-f92b2.appspot.com',
  );
}
